# Generated by Django 2.2.9 on 2020-02-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_name', models.CharField(max_length=100)),
                ('Emp_email', models.EmailField(max_length=50)),
                ('Emp_phonNO', models.IntegerField(default=0)),
                ('Emp_dept', models.CharField(default='NA', max_length=25)),
            ],
        ),
    ]
