# Generated by Django 2.2.9 on 2020-02-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimeet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=100)),
                ('stud_last', models.EmailField(max_length=50)),
                ('stud_country', models.IntegerField(max_length=10)),
                ('stud_subject', models.CharField(default='NA', max_length=200)),
            ],
        ),
    ]
