# Generated by Django 2.2.9 on 2020-02-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimeet', '0002_studentdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='stud_country',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='stud_last',
            field=models.CharField(max_length=50),
        ),
    ]
